name: flutter_recaptcha_v2_compat
description: Flutter plugin for Google ReCaptcha V2 – Simplify captcha integration in your Flutter app effortlessly.
version: 1.0.4
homepage: https://github.com/corgivn/flutter_recaptcha_v2/

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.4
  http: ^1.2.0
  intl: ^0.19.0
  flutter_svg: ^2.0.3
  auto_route: ^8.1.2
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  enum_annotation: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  flutter_gen_runner: ^5.3.2
  intl_utils: ^2.8.5
  auto_route_generator: ^8.0.0
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false

  assets:
    enabled: true
    outputs:
      class_name: RCAssets
      package_parameter_enabled: true
      style: dot-delimiter

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter_intl:
  enabled: true
  main_locale: 'en'
  arb_dir: assets/l10n